<h1 style="color: #83eac2;">02 - Limpieza, EDA y Feature Engineering</h1>

---

### 2.1. Importar los paquetes y módulos necesarios a lo largo del notebook.

In [ ]:
# ============ IMPORTS ========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### 2.2. Cargar Datos

In [8]:
df = pd.read_csv('../data/raw/ER Wait Time Dataset.csv')
print(f'Shape: {df.shape}')

Shape: (5000, 19)

### 2.3. Mostrando la información básica del dataset

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Visit ID                            5000 non-null   str
 1   Patient ID                          5000 non-null   str
 2   Hospital ID                         5000 non-null   str
 3   Hospital Name                       5000 non-null   str
 4   Region                              5000 non-null   str
 5   Visit Date                          5000 non-null   str
 6   Day of Week                         5000 non-null   str
 7   Season                              5000 non-null   str
 8   Time of Day                         5000 non-null   str
 9   Urgency Level                       5000 non-null   str
 10  Nurse-to-Patient Ratio              5000 non-null   int64
 11  Specialist Availability             5000 non-null   int64
 12  Facility Size (Beds)                5000 non-null   int64
 13  Time to Registration (min)          5000 non-null   int64
 14  Time to Triage (min)                5000 non-null   int64
 15  Time to Medical Professional (min)  5000 non-null   int64
 16  Total Wait Time (min)               5000 non-null   int64
 17  Patient Outcome                     5000 non-null   str
 18  Patient Satisfaction                5000 non-null   int64
dtypes: int64(8), str(11)
memory usage: 742.3 KB

### 2.4. Verificando las variables númericas

In [11]:
df.describe()

,Nurse-to-Patient Ratio,Specialist Availability,Facility Size (Beds),Time to Registration (min),Time to Triage (min),Time to Medical Professional (min),Total Wait Time (min),Patient Satisfaction
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,3.238200,3.875000,87.118800,11.704200,24.827000,45.385400,81.916600,2.771600
std,1.200895,3.043292,57.998585,10.437284,24.807994,35.619975,68.084538,1.424584
min,1.000000,0.000000,10.000000,0.000000,1.000000,2.000000,4.000000,1.000000
25%,3.000000,1.000000,36.000000,3.000000,6.000000,17.000000,27.000000,1.000000
50%,3.000000,3.000000,74.000000,8.000000,16.000000,35.000000,60.000000,3.000000
75%,4.000000,6.000000,138.000000,18.000000,36.000000,66.000000,122.000000,4.000000
max,5.000000,10.000000,200.000000,66.000000,163.000000,233.000000,442.000000,5.000000

### 2.5. Mostrando las primeras filas

In [10]:
df.head()

,Visit ID,Patient ID,Hospital ID,Hospital Name,Region,Visit Date,Day of Week,Season,Time of Day,Urgency Level,Nurse-to-Patient Ratio,Specialist Availability,Facility Size (Beds),Time to Registration (min),Time to Triage (min),Time to Medical Professional (min),Total Wait Time (min),Patient Outcome,Patient Satisfaction
0,HOSP-1-20240210-0001,PAT-00001,HOSP-1,Springfield General Hospital,Urban,2024-02-10 20:20:56,Saturday,Winter,Late Morning,Medium,4,3,92,17,22,66,105,Discharged,1
1,HOSP-3-20241128-0001,PAT-00002,HOSP-3,Northside Community Hospital,Rural,2024-11-28 02:07:47,Thursday,Fall,Evening,Medium,4,0,38,9,30,30,69,Discharged,3
2,HOSP-3-20240930-0002,PAT-00003,HOSP-3,Northside Community Hospital,Rural,2024-09-30 04:02:28,Monday,Fall,Evening,Low,5,1,38,38,40,125,203,Discharged,1
3,HOSP-2-20240227-0001,PAT-00004,HOSP-2,Riverside Medical Center,Urban,2024-02-27 00:31:13,Tuesday,Winter,Evening,High,4,5,94,8,16,64,88,Discharged,2
4,HOSP-1-20240306-0002,PAT-00005,HOSP-1,Springfield General Hospital,Urban,2024-03-06 16:52:26,Wednesday,Spring,Afternoon,Low,4,8,74,26,29,63,118,Discharged,1

### 2.6. Verificando valores Nulos

In [ ]:
df.isnull().all()

Visit ID                              False
Patient ID                            False
Hospital ID                           False
Hospital Name                         False
Region                                False
Visit Date                            False
Day of Week                           False
Season                                False
Time of Day                           False
Urgency Level                         False
Nurse-to-Patient Ratio                False
Specialist Availability               False
Facility Size (Beds)                  False
Time to Registration (min)            False
Time to Triage (min)                  False
Time to Medical Professional (min)    False
Total Wait Time (min)                 False
Patient Outcome                       False
Patient Satisfaction                  False
dtype: bool

<font color= #6e77f3>***Se confirma que no hay nulos***</font>


### 2.7. Verificación de duplicados

In [17]:
print(f'Filas duplicadas: {df.duplicated().sum()}')

Filas duplicadas: 0

<font color= #6e77f3>***Se confirma que no hay duplicados***</font>